resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/redhat-user-workloads/rhwa-tenant/self-node-remediation/snr-operator-0-11
  newTag: snr-operator-0-11-on-pull-request-n67wt-build-container
